---
title: "Homework Requirements"
output:
  pdf_document: default
  html_document:
    theme: readable
urlcolor: blue
header-includes:
  - \usepackage{booktabs}
  - \usepackage{float}
  - \usepackage{array}
---

Read carefully. Failure to meet the formatting requirements described below may result in point deductions on the homework assignment.

1. Assignments must be submitted through Canvas as a single PDF file. Late assignments will be penalized by one point (out of 10 possible) if submitted within 12 hours after the deadline, and one point more for each additional 12 hour interval. For example, and assignment that is late by one minute will be penalized by one point. An assignment that is turned in 13 hours after it is due will be penalized by two points. 

0. Your solutions must be typed and *very* neatly organized. 

0. You may use [R Markdown](https://rmarkdown.rstudio.com) if you know how to use it properly. 

0. You must include with your solutions the relevant R output to answer the question and the code that produced it. Include the code within the solution, not in an appendix. You should provide enough code so that I can replicate your results. 

0. Use a [monospaced font](https://en.wikipedia.org/wiki/Monospaced_font) for all R code and output. Do not submit screen shots of code or output. Cut-and-paste from R as needed, or use R Markdown. 

0. Do not put written responses as comments in R Markdown. 

0. Format your code so that it does not run off the page or wrap around the page awkwardly. You might find it useful to use something like `options(digits = 4)` to reduce the number of reported digits.

0. Mathematical expressions need not be typeset perfectly, but they should be clear. For example, you might use "b1" instead of $\beta_1$.

0. Do not include the original question or instructions with your solutions, and do not include any R code and output from the question that I provided for background that is not needed for your solution.

0. You are permitted to discuss the homework with other students in the course. But all of your work including code, output, and your written answers must be your own. Copying code/output/solutions or otherwise turning in work that is not your own may result in a referral to the Dean of Students and grade of F for the course. 

0. Use of artificial intelligence (AI) is limited to helping with basic coding questions. You may not use it to attempt to answer questions in full. Your code, output, and any text in your solution must be your own (similar to my policy on working with others). Copying code/output/solutions or otherwise turning in work from AI may result in a referral to the Dean of Students and grade of F for the course. 

0. You are welcome to ask me questions. I will be happy to clarify what I am asking in any of the questions and may provide you some help with solving problems by showing you how to work through similar problems from class. I will also be open to helping with any R problems/errors. If you email me with a R question it will usually be helpful for you to include enough of your R script so that I can replicate your issue. But please avoid saving your questions to just before the assignment is due. I can usually respond quickly to questions, but I will sometimes need time to respond depending on my schedule. 

